ArrayList<Button> buttons = new ArrayList<Button>();
Button close;
ArrayList<Enemy> enemys = new ArrayList<Enemy>();
SoundFile elimSound;
SoundFile hitSound;
float eSize;
float effectTime;
float rotSpeed = .01;
float maxEnemys = 8;
float fHealth = 100;
float volume = .03;
int red = 255;
int green = 255;
int blue = 255;
FPSCamera cam;
GLWindow r;
float zoom = 3;
float zoomer = 0;
float maxZoom = 6;
PVector view;
float Sensitivity;
boolean[] keys = new boolean[256];
boolean mouseLock;
int offsetX=0;
int offsetY=0;
PVector oldMouse;
boolean settings;
int clicked = -1;
float recoil = .001;
String[] headings = {"Enemy Size:", "Sensitivity:", "Max Rotation Speed: ", "Enemys: ", "Zoom Amount:", "Enemy Health: ", "Volume: ", "Movement Speed: ", "Recoil:", "Wall Red: ", "Wall Green: ", "Wall Blue: "};
int[] data = new int[headings.length];
